config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  devise_for :user

  resources :projects
  resources :tickets
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    # Manager
    if user.user_type == 'manager'
      can %i[read edit destroy], Project, user_id: user.id
      can [:create], Project
      can [:read], Ticket

    end

    # QA
    if user.user_type == 'QA'
      can [:read], Project, user_projects: { user_id: user.id }
      can [:create], Ticket
      can %i[read edit destroy], Ticket, user_id: user.id
    end

    # Developer
    return unless user.user_type == 'Developer'

    can [:read], Project, user_projects: { user_id: user.id }
    can [:read], Ticket, project: { user_projects: { user_id: user.id } }
    can [:edit], Ticket do |ticket|
      ticket.developer.nil? || ticket.developer_id == user.id
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :name, presence: true

  belongs_to :user

  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :tickets
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  belongs_to :project
  belongs_to :user
  belongs_to :developer, class_name: 'User', optional: true
  validates :title, presence: true, uniqueness: { scope: :project_id }
  validates :category, presence: true
  validates :status, presence: true

  mount_uploader :image_url, ImageUploader
end

app/models/user.rb
# frozen_string_literal: true

# user model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum user_type: { manager: 0, QA: 1, Developer: 2 }
  validates :user_type, presence: true
  validates :name, presence: true

  has_many :projects
  has_many :user_projects
  has_many :assigned_projects, through: :user_projects, source: :project

  has_many :tickets

  def related_project
    if manager?
      projects
    else
      assigned_projects
    end
  end
end

app/models/user_project.rb
# frozen_string_literal: true

class UserProject < ApplicationRecord
  validates :user_id, presence: true
  validates :project_id, presence: true

  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# app controller
class ApplicationController < ActionController::Base
  include Pagy::Backend
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |_exception|
    flash[:danger] = 'You are not authorized to access this'
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :user_type) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password, :user_type)
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# pages Controller
class PagesController < ApplicationController
  def home; end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Project class
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  def index
    authorize! :read, Project
    if current_user
      @pagy, @projects = pagy(current_user.related_project, items: 3)
    else
      redirect_to root_path
    end
  end

  def new
    @project = Project.new
    authorize! :create, @project
  end

  def create
    @project = Project.new(params.require(:project).permit(:name, :description))
    @project.user = current_user
    authorize! :create, @project
    if @project.save
      @project.update(project_params)
      flash[:success] = 'Project was created successfully!'
      redirect_to project_path(@project)
    else
      render 'new', status: 300
    end
  end

  def show
    authorize! :read, @project
    @pagy, @tickets = pagy(@project.tickets, items: 5)
  end

  def edit
    authorize! :edit, @project
    @users = @project.users
  end

  def update
    authorize! :edit, @project
    if @project.update(project_params)
      flash[:success] = 'Project was updated successfully!'
      redirect_to project_path(@project)
    else
      render 'edit'

    end
  end

  def destroy
    authorize! :destroy, @project
    @project.destroy
    flash[:success] = 'Project was deleted successfully!'
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, user_ids: [])
  end

  def set_project
    @project = Project.find(params[:id])
  end

  # def related_project
  #   if current_user.manager?
  #     current_user.projects
  #   else
  #     current_user.assigned_projects
  #   end
  # end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

# Ticket class
class TicketsController < ApplicationController
  # def index
  #   if current_user.assigned_projects.map(&:id).include?(params[:id].to_i)
  # || Project.find(params[:id].to_i).user_id == current_user.id
  #     @tickets = Project.find(params[:id]).tickets
  #     authorize! :read, Ticket
  #     @project = params[:id]
  #   else
  #     flash[:danger] = 'You are not allowed to view this page'
  #     redirect_to root_path
  #   end
  # end

  def show
    @ticket = Ticket.find(params[:id])
    authorize! :read, @ticket
  end

  def new
    @project = params[:id]
    @pro = Project.find(params[:id].to_i)
    authorize! :create, Ticket
    # binding.pry
    if current_user.user_type == 'QA'
      @ticket = Ticket.new
    else
      redirect_to @root_path
    end
  end

  def create
    @pro = Project.find(ticket_params[:project_id].to_i)
    @ticket = Ticket.new(ticket_params)
    authorize! :create, @ticket
    @ticket.user_id = current_user.id
    # binding.pry
    if @ticket.save
      # binding.pry
      flash[:success] = 'Bug was created successfully!'
      redirect_to ticket_path(@ticket)
    else
      # binding.pry
      render 'new', status: 300
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
    authorize! :edit, @ticket
  end

  def update
    @ticket = Ticket.find(params[:id])
    authorize! :edit, @ticket

    if @ticket.update(ticket_params)
      flash[:success] = 'Bug was updated successfully!'
      redirect_to ticket_path(@ticket)
    else
      render 'edit'

    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @project = @ticket.project.id
    authorize! :destroy, @ticket
    @ticket.destroy
    flash[:success] = 'Bug was updated successfully!'
    redirect_to tickets_path(id: @project)
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :description, :category, :status, :deadline, :project_id, :user_id,
                                   :image_url, :developer_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%= link_to "Bug Tracking System", root_path, class: "navbar-brand", id: "logo" %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a><%= link_to "Home", root_path, class: "nav-link"%></a>
        </li>
        <% if current_user %>
        <% if current_user.user_type == "manager" %>
        <li class="nav-item">
          <a><%= link_to "Create Project", new_project_path, class: "nav-link"%></a>
        </li>
        <%end%>
        <li class="nav-item">
          <a><%= link_to "Projects", projects_path, class: "nav-link"%></a>
        </li>
        <%end%>
      </ul>
    </div>
    <% if current_user %>
      <div class="mx-3">
        <a><%= current_user.name%></a>
      </div>
      <button class="btn btn-outline-dark"><%= link_to "Logout", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "nav-link"%></button>
    <%else%>
        <button class="btn btn-outline-dark"><%= link_to "SignUp", new_user_registration_path, class: "nav-link" %></button> |
        <button class="btn btn-outline-dark"><%= link_to "LogIn", new_user_session_path, class: "nav-link" %></button>
    <%end%>
  </div>
</nav>  

app/views/layouts/_messages.html.erb
<div class="row mx-auto" >
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTrackingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<center>
<br>
<br>
<div class="w-50 p-5 text-center bg-image rounded-3 center" style="
    background-image: url('https://www.techslang.com/wp-content/uploads/2021/08/9359-e1629798707656.jpg');
    height: 400px;
  ">
  <div class="mask" >
    <div class="d-flex justify-content-center align-items-center">
      <div class="text-white">
        <h1 class="mb-3 text-dark">Welcome to Bug Tracking</h1>
        <br>
        <h4 class="mb-3 text-muted">The best Bug Tracking App!</h4>
        <br>
        <br>
        <br>
        <br>
        <% if !current_user%>
        <%= link_to "LogIn", new_user_session_path, class: "btn btn-dark btn-lg" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if current_user %>
  <%if current_user.user_type != "manager" %>
<br>
<br>
  <%= link_to "Show Assigned Projects", projects_path, class: "btn btn-dark btn-lg" %>
<%else%>
<br>
<br>
  <%= link_to "Show Projects", projects_path, class: "btn btn-dark btn-lg" %>
  <%end%>
<%end%>
</center>

app/views/projects/_projects.html.erb
<div class="row rounded w-50 p-3">
<table class="table table-borderless table-hover table-striped">
 <caption>List of projects</caption>
  <thead>
    <tr>
      <th scope="col" class="text-center">#</th>
      <th scope="col" class="text-center">Project Name</th>
      <th scope="col" class="text-center">No. of Bugs</th>
      <th scope="col" class="text-center">Created by</th>
    </tr>
  </thead>
  <tbody>
  <% objects.each.with_index(1) do |project, i| %>   
    <tr>
      <th scope="row" class="text-center"><%= i%></th>
      <td class="text-center"><%= link_to project.name, project_path(project)%></td>
      <td class="text-center"><%= project.tickets.count%></td>
      <td class="text-center"><%= project.user.name.capitalize%></td>
    </tr>
    <%end%>
  </tbody>
</table>
  <%== pagy_info(pagy)%> 
  <br>
  <br>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/projects/edit.html.erb
<center>
<h1 align="center">Edit Project</h1>
<hr>
<div class="col-md-12 w-50 p-3">
    <%= form_for(@project, :html => {class:"form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-md-2">
                <%= f.label :name %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :name, class: "form-control", placeholder: "Name of project", autofocus: true%>
            <div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                <%= f.label :description %>
            </div>
            <div class="col-md-12">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter project details" %>

            </div>
        </div>
<br>


          <div class="form-group">
            <div class="control-label col-md-3">
                <%= f.label :developer, "Add Resources" %>
            </div>
            <div class="col-md-14">
                <%= f.select :user_ids, options_from_collection_for_select(User.not_manager, :id, proc {|user| "#{user.name} (#{user.user_type})"} , :selected =>  @users.map(&:id)), {}, class: "multiselect rounded md-8 form-control", multiple: true%>

            <div>
        </div>
<br>
<br>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <%= f.submit class: "btn btn-primary btn-lg"%>
            </div>
        </div>
    <%end%>    
     <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request", project_path(@project) %> ]
    </div>
</div>
</center> 

app/views/projects/index.html.erb
<h1 style="text-align:center">List of All Projects</h1>
<hr>
<p style="color: green"><%= notice %></p>
<center>
<% if current_user.user_type == "manager" %>
  <%= link_to "New project", new_project_path, class: "btn btn-dark btn-lg"  %>   
  <br>
  <br>
  <% if @projects.count != 0 %>
    <%= render "projects", objects: @projects, pagy: @pagy %>
  <% else %>
    <p>You have not created any projects yet</p>
  <% end %>
<% end %>

<% if current_user.user_type == "QA" %>
  <% if @projects.count != 0 %>
    <h4>Your Assigned Project to  Assure Quality</h4>
    <%= render "projects", objects: @projects, pagy: @pagy %>
  <% else %>
    <p>You have not been assigned to any project to assure quality</p>
  <% end %>
<% end %>

<%  if current_user.user_type == "Developer"  %>
  <% if @projects.count != 0 %>
    <h4>Your Assigned Project to develop</h4>
    <%= render "projects", objects: @projects, pagy: @pagy %>
  <% else %>
      <p>You have not been assigned to any project to develop</p>

  <% end %>
<% end %>

</center>

app/views/projects/new.html.erb
<center>
<h1 align="center">Create new Project</h1>
<hr>
<%= render 'shared/errors', obj: @project %>
<div class="col-md-12 w-50 p-3">
    <%= form_for(@project, :html => {class:"form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-md-2">
                <%= f.label :name %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :name, class: "form-control", placeholder: "Name of project", autofocus: true%>
            <div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                <%= f.label :description %>
            </div>
            <div class="col-md-12">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter description of project" %>

            </div>
        </div>
<%# <br>
        <div class="form-group">
            <div class="control-label col-md-2">
                <%= f.label :Qa, "Add Q/A" %>
            <%# </div> %>
            <%# <div class="col-md-8"> %>
                <%# <%= f.select :user_ids, options_from_collection_for_select(User.where(user_type: 1), :id, :name), {}, class: "multiselect rounded md-8 form-control", multiple: true %>
            <%# <div> %>
        <%# </div> %>
<br>


          <div class="form-group">
            <div class="control-label col-md-3">
                <%= f.label :developer, "Add Resources" %>
            </div>
            <div class="col-md-14">
                <%= f.select :user_ids, options_from_collection_for_select(User.where.not(user_type: 0), :id, proc {|user| "#{user.name} (#{user.user_type})"} ), {}, class: "multiselect rounded md-8 form-control", multiple: true%>
                <%# <%= f.select :user_ids, options_from_collection_for_select(User.where(user_type: 2), :id, :name), {}, class: "multiselect rounded md-8 form-control", multiple: true %>
            <div>
        </div>
<br>
<br>


        <br>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <%= f.submit class: "btn btn-primary btn-lg"%>
            </div>
        </div>
    <%end%>    
     <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request", root_path %> ]
    </div>
</div>
</center>

app/views/projects/show.html.erb
<center>
<h1 align="center" >Project Name: <%= @project.name.capitalize%></h1>
<div class="well col-md-8 col-md-offset-2" align="center"> 
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr/>
    <%= @project.description %>

<br>
<br>

    <p>
        Created by: 
        <small>
            <%= @project.user.email%>
        </small>
        <div class="pull-right">
            Created: <%= time_ago_in_words(@project.created_at)%> ago
        </div>
   </p>
   <div class="recipe-actions" align="center">
   <% if current_user == @project.user%>
   <br>
    <%= link_to "Edit this Project", edit_project_path(@project), class: "btn btn-xs btn-warning"%>
    <br>
    <br>

    <%= button_to "Delete this project", project_path(@project),  method: :delete, class: "btn btn-xs btn-danger"%>
    <%end%>
    <br>
    <%= link_to "Go Back", projects_path, class: "btn btn-xs btn-primary"%>
   </div>
   <br>
   <% if current_user.user_type == "QA" %>
        <%= link_to "Create Bug", new_ticket_path(id: @project), class: "btn btn-outline-dark btn-lg"%>
        <br>
        <br>
    <%end%>
    <h5>Bug List</h5>
    <br>
    <%if @tickets.count == 0%>
        <h6>No Bugs to show</h6>
    <%else%>
        <%= render 'tickets/tickets', objects: @tickets, pagy: @pagy %>
    <%end%>
   
</div>
</center>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row w-50 p-3 border border-danger rounded" style="background: rgba(255,211,218,255)">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h6 class="panel-title">
            <%# <%binding.pry%>
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
          </h6>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li class="text-danger"><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>  
      </div>
    </div>
  </div>
<% end %>

app/views/tickets/_tickets.html.erb
<div class="row rounded w-50 p-3" style="margin-bottom: 10px">
<table class="table table-borderless table-hover table-striped">
 <caption>List of bugs</caption>
  <thead>
    <tr>
      <th scope="col" class="text-center">#</th>
      <th scope="col" class="text-center">Bug Name</th>
      <th scope="col" class="text-center">Status</th>
      <th scope="col" class="text-center">Type</th>
      <th scope="col" class="text-center">Created by</th>
    </tr>
  </thead>
  <tbody>
  <% objects.each.with_index(1) do |ticket, i| %>   
    <tr>
      <th scope="row" class="text-center"><%= i%></th>
      <td class="text-center"><%= link_to ticket.title, ticket_path(ticket)%></td>
    <% if ticket.status == 0 %>
        <td class="text-center"><b class="text-primary">New</b></td>
    <% elsif ticket.status == 1 %>
        <td class="text-center"><b class="text-warning">Started</b></td>
    <% elsif ticket.status == 2 && ticket.category == 0 %>
        <td class="text-center"><b class="text-success">Resolved</b></td>
    <% else %>
        <td class="text-center"><b class="text-success">Completed</b></td>
    <% end %>
      <%if ticket.category == 0%>
        <td class="text-center">Feature</td>
      <%else%>
        <td class="text-center">Bug</td>
      <%end%>
      <td class="text-center"><%= ticket.user.name.capitalize%></td>
    </tr>
<%end%>
  </tbody>
</table>
<%== pagy_info(pagy)%> 
<br>
<br>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/tickets/edit.html.erb
<center>
<h1 align="center">Edit Bug</h1>
<hr>
<%= render 'shared/errors', obj: @ticket %>

<div class="col-md-12 w-50 p-3">
    <%= form_for(@ticket, :html => {class:"form-horizontal", role: "form"}) do |f| %>
    <%if current_user.user_type == "QA"%>
        <%= f.hidden_field :status, value: 0%>

        <div class="form-group">
            <div class="control-label col-md-2">
                <%= f.label :title %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :title, class: "form-control", placeholder: "Name of ticket", autofocus: true%>
            <div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                <%= f.label :description %>
            </div>
            <div class="col-md-12">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter description of bug" %>
            </div>
        </div>
        <br>
        <div class="form-group">  
            <div class="control-label col-md-3">
                <%= f.label :image, "Change Image" %>
            </div>
            <div class="col-md-12">
                <%= f.file_field :image_url, class:"rounded md-8 form-control"  %> 
            </div>
        </div>    
            <%if @ticket.image_url.present? %>
                <div class="my-5">
                 <%= image_tag @ticket.image_url.custom.url%>
                </div>
            <%end%>
        </div>
        <br>
        <div class="form-group">
            <div class="control-label col-md-3">
                <%= f.label :developer_id, "Change Developer" %>
            </div>
            <div class="col-md-8">
                <%= f.select :developer_id, options_for_select(@ticket.project.users.where(user_type: 2).map { |dev| [dev.name, dev.id] }), {}, class:"rounded md-8 form-control" %>
            </div>
        </div>
        <br>
        <br>
        <div class="form-group">
            <div class="control-label col-md-3">
                <%= f.label :Deadline, "Add Deadline" %>
            </div>
            <div class="col-md-8">
                <%= f.date_field :deadline, "data-provide" => 'datepicker', class: "rounded md-8 form-control"%>
            </div>
        </div>
        <%end%>        

        <% if current_user.user_type == "Developer"%>
            <div class="form-group">  
                 <div class="control-label col-md-3">
                    <%= f.label :Status, "Change Status" %>
                </div>
                <div class="col-md-8">
                    <%= f.select :status, [['Started', 1], ['Completed', 2]], {}, class:"rounded md-8 form-control" %>
                </div>
            </div>
        <%end%>
        <br>
        <br>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10"> 
                <%= f.submit class: "btn btn-primary btn-lg"%>
            </div>
        </div>
    <%end%>    
   
      
     <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request", ticket_path(@ticket) %> ]
    </div>
</div>
</center>

app/views/tickets/index.html.erb
<h1 style="text-align:center">List of All Bugs</h1>
<hr>
<p style="color: green"><%= notice %></p>
<center>
<% if current_user.user_type == "manager" %>
    <% if @tickets.count != 0 %>
        <%= render "tickets", objects: @tickets %>

      <% else %>
        <p>No Bugs yet reported</p>

      <% end %>
<%end%>
<% if current_user.user_type == "QA" %>
    <%= link_to "Create Bug", new_ticket_path(id: @project), class: "btn btn-outline-dark btn-lg"%>
    <br>
    <br>
  <% if @tickets.count != 0 %>
<%= render "tickets", objects: @tickets %>

  <% else %>
      <p>No Bugs reported</p>

  <% end %>

  <% end %>

<%  if current_user.user_type == "Developer"  %>

 <% if @tickets.count != 0 %>
<%= render "tickets", objects: @tickets %>
 <% else %>
      <p>No Bugs reported</p>

  <% end %>

<% end %>

</center>

app/views/tickets/show.html.erb
<center>
<h1 align="center" >Bug name: <%= @ticket.title.capitalize%></h1>
<h3 align="center" >Status:</h3>
<% if @ticket.status == 0%>
        <h4 class="text-primary">New</h4>
<% elsif @ticket.status == 1 %>
    <h4 class="text-warning">Started</h4>
<% elsif @ticket.status == 2 and @ticket.category = 0 %>
    <h4 class="text-success">Resolved</h4>
<%else%>
    <h4 class="text-success">Completed</h4>
<%end%>
<hr/>
<%if @ticket.image_url.present? %>
                <div class="my-5">
                 <%= image_tag @ticket.image_url.custom.url%>
                </div>
            <%end%>
<div class="well col-md-8 col-md-offset-2" align="center"> 
    <h4 class="center description">Description: </h4>
    <%= @ticket.description %>
<br>
<br>

    <p>
        Created by: 
        <small>
            <%= @ticket.user.email%>
        </small>
        <div class="pull-right">
            Created: <%= time_ago_in_words(@ticket.created_at) %> ago
        </div>
   </p>
   <div class="recipe-actions" align="center">
   <% if current_user == @ticket.user || @ticket.developer_id == current_user.id || (@ticket.developer_id == nil and current_user.user_type="Developer")%>
   <br>
    <%= link_to "Edit this BUG", edit_ticket_path(@ticket), class: "btn btn-xs btn-warning"%>
    <br>
    <%end%>
     <% if current_user == @ticket.user %>
    <br>
    <%= button_to "Delete this BUG", ticket_path(@ticket),  method: :delete, class: "btn btn-xs btn-danger"%>
    <%end%>
    <br>
    <% if current_user.user_type != "maneger"%>
    <%= link_to "Go Back", project_path(@ticket.project), class: "btn btn-xs btn-primary"%>
    <br>
    <%end%>
   </div>
</div>
</center>